### ISSUE TITLE
Tutorial Error

### ISSUE THREAD

**Issue by enplan** [divio/django-polls#3]
Receiving the following error attempting to download via powershell:

(env) PS C:\users\jclarke\tutorial-project> pip install -e git+https://git@github.com/divio/django-polls.git#egg=django-polls
Obtaining django-polls from git+https://git@github.com/divio/django-polls.git#egg=django-polls
  Cloning https://git@github.com/divio/django-polls.git to c:\users\jclarke\env\src\django-polls
  Error [Error 2] The system cannot find the file specified while executing command git clone -q https://git@github.com/divio/django-polls.git c:\users\jclarke\env\src\django-polls
Cannot find command 'git'

**Comment by FinalAngel** [comment]
@enplan you will have to install git on your window machine: https://git-scm.com/download/win
