### ISSUE TITLE
__init__.py does not propogate during installation

### ISSUE THREAD

**Issue by geoidesic** [divio/django-polls#5]
The documents on the following link suggest installation of this repo's application:
http://docs.django-cms.org/en/latest/introduction/plugins.html#integrate-the-polls-cms-integration-application

i.e. 
`pip install -e git+http://git@github.com/divio/django-polls.git#egg=polls`

However, following those instructions does not cause the `__init__.py` file from this repo to be included for some reason (perhaps it's not included in the build?). This causes the entire tutorial to fail.

It took some debugging to realise that this was the problem and we had to manually create the `__init__.py` file before our `polls_cms_integration` app could work. Without it we were getting this error:

```
poll = models.ForeignKey(Poll)
NameError: name 'Poll' is not defined
```

**Comment by FinalAngel** [comment]
@evildmp can you check why the docs link is not reachable anymore? Its still found in the search.

**Comment by FinalAngel** [comment]
@geoidesic it should be: **polls** instead of **poll**. I checked the code and there's nothing that excludes the __ini__.py :)
