### ISSUE TITLE
Support for Django 2.2

### ISSUE THREAD

**Issue by ruggedness-mime** [divio/django-polls#8]
When running through the django CMS tutorial, I found I had to make some changes to the django-polls app used to allow it to work with Django 2.2 and [forked to put a pull request in for my changes](https://github.com/ruggedness-mime/django-polls/blob/master/polls/models.py) but in doing that, I noted that @NeodarZ had put in #7 for essentially the same changes.

I wanted to create this issue to flag their PR for merge/review to eliminate the need for jerry-rigging 2.x support.

**Comment by FinalAngel** [comment]
Thank you @NeodarZ for the pull request and thanks for the info @ruggedness-mime !
